### ISSUE TITLE
Erweiterung auf auf Map Services wünschenswert

### ISSUE THREAD

**Issue by StefanMenze** [conterra/mapapps-overviewmap#1]
Es wäre gut, wenn man nicht nur Esri Basemaps (dark-grey etc.) als Overviemap definieren könnte sondern auch eines der in einer App enthaltenen Map Services.
Da wir ein anderes Bezugssystem verwenden können wir leider nicht auf Esri Basemaps zurückgreifen

**Comment by matthiasstein** [comment]
This feature was added in https://github.com/conterra/mapapps-overviewmap/releases/tag/1.1.0
