### ISSUE TITLE
Prevent zooming with the help of Shift and the mouse

### ISSUE THREAD

**Issue by matthiasstein** [conterra/mapapps-overviewmap#2]
Currently, it is possible to draw a frame in the overview map with the help of Shift and to zoom through it. This should be prevented.

**Comment by sholtkamp** [comment]
Behavior is consistent with provided example applications.
Currently no fix can be developed as fixes of the API are required.

**Comment by sholtkamp** [comment]
Issue can no longer be replicated as of map.apps 4.13.1
